fix: Set a positive schema attribute for netbox.basepath.
Old behavior:

```> terraform plan
provider.netbox.basepath
  URL path to the netbox API.

  Enter a value:

Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
        * basepath: One of optional, required, or computed must be set
```